services:
  reclip:
    build: .
    container_name: reclip
    ports:
      - "8899:8899"
    volumes:
      - .:/app
      - /app/downloads
      - auth-data:/app/auth
      - browser-data:/browser-data
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=8899
      - POT_PROVIDER_URL=http://pot-provider:4416
    depends_on:
      - browser
      - pot-provider

  pot-provider:
    image: brainicism/bgutil-ytdlp-pot-provider:1.3.1-deno
    container_name: reclip-pot-provider
    init: true
    restart: unless-stopped

  browser:
    image: lscr.io/linuxserver/chromium:latest
    container_name: reclip-browser
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Miami
      - CUSTOM_PORT=3002
      - CHROME_CLI=https://www.youtube.com --proxy-pac-url=http://host.docker.internal:8899/proxy.pac --start-maximized
    volumes:
      - browser-data:/config
    ports:
      - "3002:3002"
    shm_size: "1gb"
    restart: unless-stopped

volumes:
  auth-data:
  browser-data:
